import {
  AudioLines,
  BrainCircuit,
  Calculator,
  CircleCheck,
  ClipboardCheck,
  Database,
  FileSearch,
  FileSpreadsheet,
  FileText,
  GitCompare,
  Inbox,
  ListChecks,
  Mail,
  MailCheck,
  Phone,
  ScanSearch,
  Search,
  Send,
  Table2,
  Tags,
  TriangleAlert,
  UserCheck,
  UserSearch,
  Hash,
  Link2,
  PenLine,
  FileDown,
  Layers,
  ServerCog,
  TrendingUp,
  NotebookPen,
  Columns3,
} from 'lucide-react'

export const ICONS = {
  phone: Phone,
  audio: AudioLines,
  brain: BrainCircuit,
  calc: Calculator,
  check: CircleCheck,
  clipboard: ClipboardCheck,
  database: Database,
  fileSearch: FileSearch,
  excel: FileSpreadsheet,
  file: FileText,
  compare: GitCompare,
  inbox: Inbox,
  tasks: ListChecks,
  mail: Mail,
  mailCheck: MailCheck,
  scan: ScanSearch,
  search: Search,
  send: Send,
  table: Table2,
  tags: Tags,
  warning: TriangleAlert,
  human: UserCheck,
  customer: UserSearch,
  hash: Hash,
  link: Link2,
  pen: PenLine,
  download: FileDown,
  layers: Layers,
  system: ServerCog,
  trend: TrendingUp,
  note: NotebookPen,
  columns: Columns3,
} as const

export type IconKey = keyof typeof ICONS
